### ISSUE TITLE
Adjust this for modinst_1.0.xx ?

### ISSUE THREAD

**Issue by iceman1001** [franzliedke/fluxbb-new-recaptcha#7]
Hi,
Nice to have this one adjusted to work with the Modinst_1.0.19 etc.  https://fluxbb.org/resources/mods/mod-installer-plugin/releases/1.0.19/
Is there some chance you will have time to do this in the near future?

**Comment by franzliedke** [comment]
Hi @iceman1001, thanks for the suggestion!

Can you quickly sum up what this would entail? Overall, there should not be too many changes needed, as this is an add on, made for easy installation. 

So yes, I am open to the idea.

**Comment by iceman1001** [comment]
And there is the limit to what I know about modinst_1.0.19 and whats required. 
I tried to modify yr project but failed,  and thats when I asked you instead. 
As I saw it, it were more about packaging of yr mod to fit in how the installer wants it.

**Comment by franzliedke** [comment]
I don't have the time to do so at the moment, I'm afraid. Maybe Otomatic can help us along?
