### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by g0dzcsgo** [franzliedke/fluxbb-new-recaptcha#8]
Is it possible to put the reCAPTCHA on the login page aswell?

**Comment by franzliedke** [comment]
I've added a checkbox to enable this for different locations. Will release this as a new version soon.

**Comment by franzliedke** [comment]
This feature has been released as part of [version 2.0.0](https://fluxbb.org/resources/mods/new-recaptcha/releases/2.0.0/).
